### ISSUE TITLE
cars_app.yaml doesn't contain java container deployment

### ISSUE THREAD

**Issue by NikitaVoitov** [tombatchelor/Cars_Sample_App#37]
Hi Tom!

Perhaps there is no Tomcat container definition in cars_app.yaml. Could you pls update yml?

**Comment by tombatchelor** [comment]
Tomcat gets deployed by Jenkins, if you look in jenkins/jenkins/jobs/AppServerBuild/config.xml you can see the YAML def for the cars-deployment that contains Tomcat
